#! python


def build(ctx):

    # Illustrate simple use of run_m_script
    ctx(
        features='run_m_script',
        source='prepare_data.m',
        target=ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat'),
        name='prepare_data'
    )
