#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='prepare_data.m',
        target=ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat'),
        name='prepare_data'
    )

    ctx(
        features='run_m_script',
        source='parameter.m',
        target=ctx.path_to(ctx, 'OUT_DATA', 'parameters.mat'),
        name='parameter'
    )

    ctx(
        features='run_m_script',
        source='simulation_data_prep.m',
        target=ctx.path_to(ctx, 'OUT_DATA', 'estimation_data.mat'),
        name='estimation_data'
    )
