#! python


def build(ctx):
    ctx(
        features='run_m_script',
        source='debt_equity_figure.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure1.pdf'),
        deps=ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat'),
        name='debt_equity_figure'
    )

    ctx(
        features='run_m_script',
        source='plot_shocks.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure2.pdf'),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'shock_innovations.mat')
        ],
        name='plot_shocks'
    )

    ctx(
        features='run_m_script',
        source='create_ar_matrix.m',
        target=ctx.path_to(ctx, 'OUT_TABLES', 'ar_matrix.tex'),
        deps=ctx.path_to(ctx, 'OUT_ANALYSIS', 'shock_innovations.mat'),
        name='create_ar_matrix'
    )

    ctx(
        features='run_m_script',
        source='baseline_model_data_plot.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure5.pdf'),
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'baseline_simulation.mat'),
            ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat')
        ],
        name='baseline_model_data_plot'
    )

    ctx(
        features='run_m_script',
        source='table_3.m',
        target=[
            ctx.path_to(ctx, 'OUT_TABLES', 'cal_params.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'est_params.tex')
        ],
        deps=ctx.path_to(ctx, 'OUT_ANALYSIS', 'extended_model_results.mat'),
        name='table_3'
    )
