#! python


def build(ctx):
    ctx(
        features='run_m_script',
        source='debt_equity_figure.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure1.pdf'),
        deps=ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat'),
        name='debt_equity_figure'
    )

    ctx(
        features='run_m_script',
        source='plot_shocks.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure2.pdf'),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'dataset.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'shock_innovations.mat')
        ],
        name='plot_shocks'
    )

    ctx(
        features='run_m_script',
        source='create_ar_matrix.m',
        target=ctx.path_to(ctx, 'OUT_TABLES', 'ar_matrix.tex'),
        deps=ctx.path_to(ctx, 'OUT_ANALYSIS', 'shock_innovations.mat'),
        name='create_ar_matrix'
    )

    # for model in 'baseline', 'max_moves_2':
    #     source = 'plot_locations'
    #     ctx(
    #         features='run_m_script',
    #         source='{}.m'.format(source),
    #         target=ctx.path_to(ctx, 'OUT_FIGURES', 'schelling_{}.png'.format(model)),
    #         deps=[
    #             ctx.path_to(ctx, 'OUT_ANALYSIS', 'schelling_{}.mat'.format(model)),
    #             ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model))
    #         ],
    #         append="('{}')".format(model),
    #         name='{}_{}'.format(source, model)
    #     )
