#! python


def build(ctx):

    ctx(
        features='tex',
        source='term_paper_main.tex',
        prompt=1,
        name='term_paper_main'
    )
    ctx.install_files(
        ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
        'term_paper_main.pdf'
    )
